### ISSUE TITLE
Likelihood not called

### ISSUE THREAD

**Issue by fredRos** [bat/bat#217] opened 2017-06-12 07:12 UTC
Dear BAT authors,

In my analysis team, we have been successfully using BAT for limit setting for some time using a framework based on BAT version 0.9.2. I wanted to update to using BAT 1.0-RC1 to see if we could benefit from some speed improvements. However, so far I have not been able to achieve much success.

I ported our code to version 1.0 and adapted code wherever interface changes had occurred. I was able to get this to compile, and I have verified the consistency in the statistical model between the setup based on 0.9.2 and the new setup by doing maximum likelihood fits using Minuit. However, the marginalization is not working. In the output, I see the following:

```
Summary : Marginalize using Metropolis
Summary : Pre-run Metropolis MCMC for model "model" ...
[4 calls to log-likelihood]
Summary :  --> Perform MCMC pre-run with 4 chains, each with maximum 100000 iterations
Error   : BCEngineMCMC::UpdateCholeskyDecompositions : chain 0 Cholesky decomposition failed! No remedies!
Error   : BCEngineMCMC::UpdateCholeskyDecompositions : chain 0 Cholesky decomposition failed! No remedies!
Error   : BCEngineMCMC::UpdateCholeskyDecompositions : chain 0 Cholesky decomposition failed! No remedies!
Error   : BCEngineMCMC::UpdateCholeskyDecompositions : chain 0 Cholesky decomposition failed! No remedies!
Error   : BCEngineMCMC::UpdateCholeskyDecompositions : chain 0 Cholesky decomposition failed! No remedies!
[repeated many more times...]
Summary :  --> Set of 4 Markov chains did not converge within 100000 iterations, and could not adjust all scales.
Summary : Run Metropolis MCMC for model "model" ...
Summary :  --> Perform MCMC run with 4 chains, each with 100000 iterations.
Summary :  --> Markov chains ran for 100000 iterations.

```
Note here that I have inserted debugging printouts into the log-likelihood function of our model, and it is only called 4 times in the very beginning! In particular, there are no calls to the log-likelihood function between

    Summary :  --> Perform MCMC run with 4 chains, each with 100000 iterations.

and

    Summary :  --> Markov chains ran for 100000 iterations.

so clearly these iterations have not been doing anything useful, and obviously the result that comes out in the end is useless.

In case it is useful to know, the BCModel we are using is a precursor of the built-in "BCMTF" called "BCMultiTemplateFitter". We prefer not to use the built-in version as we have implemented some additional functionality.

I am currently a bit stuck, so any hints on how to proceed to get to the bottom of the issue would be greatly appreciated! I am not sure whether this has to do with the errors about "Cholesky decomposition failed!", but hopefully the lack of calls to the log-likelihood function could serve as some hint in which direction to look?

Thanks in advance for any feedback!

**Comment by fredRos** [comment] 2017-06-12 07:20
I haven't seen that behavior before.  I suspect all proposed points are rejected. Perhaps that's because your prior is `log(0)`? In https://github.com/bat/bat/blob/master/src/BCModel.cxx#L86, we only call the likelihood if the prior is finite. Check for NaNs or Inf in there

```c++
double BCModel::LogProbabilityNN(const std::vector<double>& parameters)
{
    // first calculate prior (which is usually cheaper than likelihood)
    double lp = LogAPrioriProbability(parameters);
    // then calculation likelihood, or set to -inf, if prior already invalid
    double ll = (std::isfinite(lp)) ? LogLikelihood(parameters) : -std::numeric_limits<double>::infinity();;
```

Another thing to try is  if the problem persists with
```c++
SetProposeMultivariate(false);
```
before you run `MarginalizeAll()`?

**Comment by mkbugge** [comment] 2017-06-13 12:04
Thanks for these useful suggestions!

First, I inserted debugging statements into BCModel::LogProbabilityNN. This revealed that the function was only called in association with the first 4 calls to the log-likelihood, and there were no additional calls leading to inf or nan or such. So the problem seems not to be with the prior.

I then tried SetProposeMultivariate(false), and this resulted in the code running as expected and producing the correct result! It even did so faster than the code based on 0.9.2, but I am not sure this is a real improvement, or rather due to the fact that the settings seem to have changed to give 4 chains as default rather than 5 with our "medium" precision requirement.

I am guessing the switching off of "SetProposeMultivariate" means we will not take full advantage of the improvements in BAT v1.0. Do you have any suggestions how to investigate this further in order to possibly benefit from the full speed improvement of the new BAT version?

**Comment by fredRos** [comment] 2017-06-13 12:35
> First, I inserted debugging statements into BCModel::LogProbabilityNN. This revealed that the function was only called in association with the first 4 calls to the log-likelihood, and there were no additional calls leading to inf or nan or such. So the problem seems not to be with the prior.

I'm puzzled now. Do you happen to have a minimal working example? Sounds like it's independent of the actual code except for the first four values. We have many examples in our unit tests where we use the multivariate proposal and it works fine. I suspect there is some combination of options that you set that lead to this strange behavior. Please show us what you do before calling `MarginalizeAll`

> I am guessing the switching off of "SetProposeMultivariate" means we will not take full advantage of the improvements in BAT v1.0. Do you have any suggestions how to investigate this further in order to possibly benefit from the full speed improvement of the new BAT version?

How many parameters do you have? I seem to remember that there is some maximum number of parameters beyond which the multivariate is slower due to the cost of matrix operations in root. Of course, this statement depends on how fast your posterior is.

**Comment by mkbugge** [comment] 2017-06-13 13:46
Your comment inspired me to look through all operations before MarginalizeAll, and I found the problem! We had a couple of dummy parameters which were fixed by setting the lower and upper limits on the parameter ranges to the same number. Clearly this is a bit messy, and the Cholesky decomposition code must have reacted badly to this. Is there any nicer recommended way to fix a parameter in BAT? Of course, we can rewrite our model to avoid these parameters, but other users may have the same issue, e.g. if one is using the BCMTF model and want to avoid the default normalization uncertainty associated with each "process". (Essentially this is what we were doing.)

Now that we understood this, maybe an error message could be put in place to catch such an issue for other users?

Now that I can run with the multivariate proposal, I observe a speed-up beyond my wildest expectations! We have currently about 20-25 parameters in our analysis. There is much testing that remains still, but this looks extremely promising!

**Comment by oschulz** [comment] 2017-06-13 14:29
> Is there any nicer recommended way to fix a parameter in BAT?

Sure, simply do a

    GetParameter("param_name").Fix(fixed_value);

or so (after `AddParameter`).

**Comment by fredRos** [comment] 2017-06-16 12:11
> Now that we understood this, maybe an error message could be put in place to catch such an issue for other users?

Could you show use the code that led to this behavior? A snippet is enough I guess. This would help modify our code to catch this apparent bug in the future.

Perhaps we can check the parameters before running the chain. We might either warn about the empty range, or just fix the parameter and of course log that we do so.

The reason we have `GetParameter(i).Fix(0.5)` is that several people including @greenwald need this.

Thanks!

**Comment by mkbugge** [comment] 2017-06-16 13:24
No problem. The code was something like

` m->AddProcess("eBkg", Nebkg, Nebkg);
  m->AddProcess("mBkg", Nmbkg, Nmbkg);

  m->SetPriorGauss("eBkg", Nebkg, 0.1);
  m->SetPriorGauss("mBkg", Nmbkg, 0.1);
`

where "m" is a BCMTF object. This creates two parameters associated with the "eBkg" and "mBkg" processes which are both associated with zero-range intervals and dummy Gaussian priors. I would assume you can reproduce the issue by fixing a parameter in such an ad-hoc way within any of your test models and try running the marginalization with multivariate proposal.

**Comment by fredRos** [comment] 2017-06-21 09:46
Yes, I can confirm the bug. I just added a dummy parameter to the `errorpropagation` example 

```c++
 AddParameter("harr", 1., 1.);
```

With the multivariate proposal, the likelihood is called 43 (?) times. With the factorized proposal, there are 1103597 (?) calls. With 4 chains and 10^5 iterations in prerun and main run, I would expect about 8*10^5 because the prerun fails as the likelihood is flat in the dummy parameter so the efficiency can't be adjusted. Understanding the number is a separate issue, though.

**Closed** 2017-07-07 14:46 UTC
Labels: question
