### ISSUE TITLE
Parallelization no longer installed correctly.

### ISSUE THREAD

**Issue by greenwald** [bat/bat#273] opened 2018-04-17 14:06 UTC
Commit 5358d137aca1585dc875fd972c430f2b70288b7d has broken my BAT!

> ../../../../src/.libs/libBAT.so: undefined reference to `omp_get_max_threads'
> ../../../../src/.libs/libBAT.so: undefined reference to `omp_get_thread_num'

**Comment by oschulz** [comment] 2018-04-17 14:47
Duplicate of #272.

**Closed by oschulz** 2018-04-17 14:47 UTC
Labels: bug
